In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_html("https://stats.espncricinfo.com/ci/engine/records/bowling/most_wickets_career.html?id=14452;type=tournament")

In [3]:
for idx,table in enumerate(df):
    print('*'*12)
    print(idx)
    print(table)

************
0
                           Player                            Mat  \
0                       YS Chahal                             17
1              (Rajasthan Royals)             (Rajasthan Royals)
2                    PWH de Silva                             16
3   (Royal Challengers Bangalore)  (Royal Challengers Bangalore)
4                        K Rabada                             13
..                            ...                            ...
91        (Kolkata Knight Riders)        (Kolkata Knight Riders)
92                      AS Joseph                              9
93               (Gujarat Titans)               (Gujarat Titans)
94                       M Jansen                              8
95          (Sunrisers Hyderabad)          (Sunrisers Hyderabad)

                             Inns                          Overs  \
0                              17                           68.0
1              (Rajasthan Royals)             (Rajasthan Royals)
2                              16                           57.0
3   (Royal Challengers Bangalore)  (Royal Challengers Bangalore)
4                              13                           48.0
..                            ...                            ...
91        (Kolkata Knight Riders)        (Kolkata Knight Riders)
92                              9                           30.0
93               (Gujarat Titans)               (Gujarat Titans)
94                              8                           32.0
95          (Sunrisers Hyderabad)          (Sunrisers Hyderabad)

                             Mdns                           Runs  \
0                               0                            527
1              (Rajasthan Royals)             (Rajasthan Royals)
2                               1                            430
3   (Royal Challengers Bangalore)  (Royal Challengers Bangalore)
4                               0                            406
..                            ...                            ...
91        (Kolkata Knight Riders)        (Kolkata Knight Riders)
92                              0                            264
93               (Gujarat Titans)               (Gujarat Titans)
94                              0                            274
95          (Sunrisers Hyderabad)          (Sunrisers Hyderabad)

                             Wkts                            BBI  \
0                              27                           5/40
1              (Rajasthan Royals)             (Rajasthan Royals)
2                              26                           5/18
3   (Royal Challengers Bangalore)  (Royal Challengers Bangalore)
4                              23                           4/33
..                            ...                            ...
91        (Kolkata Knight Riders)        (Kolkata Knight Riders)
92                              7                           2/34
93               (Gujarat Titans)               (Gujarat Titans)
94                              7                           3/25
95          (Sunrisers Hyderabad)          (Sunrisers Hyderabad)

                              Ave                           Econ  \
0                           19.51                           7.75
1              (Rajasthan Royals)             (Rajasthan Royals)
2                           16.53                           7.54
3   (Royal Challengers Bangalore)  (Royal Challengers Bangalore)
4                           17.65                           8.45
..                            ...                            ...
91        (Kolkata Knight Riders)        (Kolkata Knight Riders)
92                          37.71                           8.80
93               (Gujarat Titans)               (Gujarat Titans)
94                          39.14                           8.56
95          (Sunrisers Hyderabad)          (Sunrisers Hyderabad)

                               SR                              4  \
0                            15.1                              1
1              (Rajasthan Royals)             (Rajasthan Royals)
2                            13.1                              1
3   (Royal Challengers Bangalore)  (Royal Challengers Bangalore)
4                            12.5                              2
..                            ...                            ...
91        (Kolkata Knight Riders)        (Kolkata Knight Riders)
92                           25.7                              0
93               (Gujarat Titans)               (Gujarat Titans)
94                           27.4                              0
95          (Sunrisers Hyderabad)          (Sunrisers Hyderabad)

                                5
0                               1
1              (Rajasthan Royals)
2                               1
3   (Royal Challengers Bangalore)
4                               0
..                            ...
91        (Kolkata Knight Riders)
92                              0
93               (Gujarat Titans)
94                              0
95          (Sunrisers Hyderabad)

[96 rows x 13 columns]
************
1
                                                   0
0  Records includes the following current or rece...
1  Gujarat Titans v Rajasthan Royals at Ahmedabad...
2  Rajasthan Royals v Royal Challengers Bangalore...
3  Lucknow Super Giants v Royal Challengers Banga...

In [8]:
bowler=df[0]

In [9]:
bowler

,Player,Mat,Inns,Overs,Mdns,Runs,Wkts,BBI,Ave,Econ,SR,4,5
0,YS Chahal,17,17,68.0,0,527,27,5/40,19.51,7.75,15.1,1,1
1,(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals)
2,PWH de Silva,16,16,57.0,1,430,26,5/18,16.53,7.54,13.1,1,1
3,(Royal Challengers Bangalore),(Royal Challengers Bangalore),(Royal Challengers Bangalore),(Royal Challengers Bangalore),(Royal Challengers Bangalore),(Royal Challengers Bangalore),(Royal Challengers Bangalore),(Royal Challengers Bangalore),(Royal Challengers Bangalore),(Royal Challengers Bangalore),(Royal Challengers Bangalore),(Royal Challengers Bangalore),(Royal Challengers Bangalore)
4,K Rabada,13,13,48.0,0,406,23,4/33,17.65,8.45,12.5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,(Kolkata Knight Riders),(Kolkata Knight Riders),(Kolkata Knight Riders),(Kolkata Knight Riders),(Kolkata Knight Riders),(Kolkata Knight Riders),(Kolkata Knight Riders),(Kolkata Knight Riders),(Kolkata Knight Riders),(Kolkata Knight Riders),(Kolkata Knight Riders),(Kolkata Knight Riders),(Kolkata Knight Riders)
92,AS Joseph,9,9,30.0,0,264,7,2/34,37.71,8.80,25.7,0,0
93,(Gujarat Titans),(Gujarat Titans),(Gujarat Titans),(Gujarat Titans),(Gujarat Titans),(Gujarat Titans),(Gujarat Titans),(Gujarat Titans),(Gujarat Titans),(Gujarat Titans),(Gujarat Titans),(Gujarat Titans),(Gujarat Titans)
94,M Jansen,8,8,32.0,0,274,7,3/25,39.14,8.56,27.4,0,0
95,(Sunrisers Hyderabad),(Sunrisers Hyderabad),(Sunrisers Hyderabad),(Sunrisers Hyderabad),(Sunrisers Hyderabad),(Sunrisers Hyderabad),(Sunrisers Hyderabad),(Sunrisers Hyderabad),(Sunrisers Hyderabad),(Sunrisers Hyderabad),(Sunrisers Hyderabad),(Sunrisers Hyderabad),(Sunrisers Hyderabad)

In [23]:
c=bowler[1:96:2]
bowling_figure=bowler[0:96:2]

In [29]:
 bowling_figure['franchise']=pd.DataFrame(c['Player'])

In [30]:
bowling_figure

,Player,Mat,Inns,Overs,Mdns,Runs,Wkts,BBI,Ave,Econ,SR,4,5,Team,franchise
0,YS Chahal,17,17,68.0,0,527,27,5/40,19.51,7.75,15.1,1,1,NaN,NaN
2,PWH de Silva,16,16,57.0,1,430,26,5/18,16.53,7.54,13.1,1,1,NaN,NaN
4,K Rabada,13,13,48.0,0,406,23,4/33,17.65,8.45,12.5,2,0,NaN,NaN
6,Umran Malik,14,14,49.1,1,444,22,5/25,20.18,9.03,13.4,1,1,NaN,NaN
8,Kuldeep Yadav,14,14,49.4,0,419,21,4/14,19.95,8.43,14.1,2,0,NaN,NaN
10,JR Hazlewood,12,12,46.3,1,377,20,4/25,18.85,8.10,13.9,1,0,NaN,NaN
12,Mohammed Shami,16,16,61.0,0,488,20,3/25,24.40,8.00,18.3,0,0,NaN,NaN
14,HV Patel,15,15,53.3,2,410,19,4/34,21.57,7.66,16.8,1,0,NaN,NaN
16,Rashid Khan,16,16,63.5,0,421,19,4/24,22.15,6.59,20.1,1,0,NaN,NaN
18,M Prasidh Krishna,17,17,66.3,3,551,19,3/22,29.00,8.28,21.0,0,0,NaN,NaN
20,T Natarajan,11,11,43.0,0,406,18,3/10,22.55,9.44,14.3,0,0,NaN,NaN
22,Avesh Khan,13,13,47.4,1,416,18,4/24,23.11,8.72,15.8,1,0,NaN,NaN
24,AD Russell,14,13,28.1,0,278,17,4/5,16.35,9.86,9.9,1,0,NaN,NaN
26,DJ Bravo,10,10,34.2,1,299,16,3/20,18.68,8.70,12.8,0,0,NaN,NaN
28,KK Ahmed,10,10,39.1,0,315,16,3/25,19.68,8.04,14.6,0,0,NaN,NaN
30,UT Yadav,12,12,48.0,2,339,16,4/23,21.18,7.06,18.0,1,0,NaN,NaN
32,Mukesh Choudhary,13,13,45.3,0,424,16,4/46,26.50,9.31,17.0,1,0,NaN,NaN
34,TA Boult,16,16,62.0,3,492,16,2/18,30.75,7.93,23.2,0,0,NaN,NaN
36,JJ Bumrah,14,14,53.2,2,383,15,5/10,25.53,7.18,21.3,0,1,NaN,NaN
38,SN Thakur,14,14,48.2,1,473,15,4/36,31.53,9.78,19.3,1,0,NaN,NaN
40,Mohsin Khan,9,9,33.0,2,197,14,4/16,14.07,5.96,14.1,1,0,NaN,NaN
42,TG Southee,9,9,35.0,0,275,14,3/20,19.64,7.85,15.0,0,0,NaN,NaN
44,RD Chahar,13,13,46.4,1,360,14,3/25,25.71,7.71,20.0,0,0,NaN,NaN
46,JO Holder,12,12,41.3,0,391,14,3/31,27.92,9.42,17.7,0,0,NaN,NaN
48,DR Sams,11,11,42.0,0,370,13,4/30,28.46,8.80,19.3,1,0,NaN,NaN
50,Ravi Bishnoi,14,14,54.0,0,456,13,2/22,35.07,8.44,24.9,0,0,NaN,NaN
52,M Theekshana,9,9,35.0,0,261,12,4/33,21.75,7.45,17.5,1,0,NaN,NaN
54,B Kumar,14,14,52.1,2,383,12,3/22,31.91,7.34,26.0,0,0,NaN,NaN
56,LH Ferguson,13,13,47.4,0,427,12,4/28,35.58,8.95,23.8,1,0,NaN,NaN
58,R Ashwin,17,17,67.0,0,503,12,3/17,41.91,7.50,33.5,0,0,NaN,NaN
60,OC McCoy,7,7,25.5,0,237,11,3/23,21.54,9.17,14.0,0,0,NaN,NaN
62,Yash Dayal,9,9,32.0,0,296,11,3/40,26.90,9.25,17.4,0,0,NaN,NaN
64,KH Pandya,14,12,38.0,1,265,10,3/19,26.50,6.97,22.8,0,0,NaN,NaN
66,Arshdeep Singh,14,14,50.0,0,385,10,3/37,38.50,7.70,30.0,0,0,NaN,NaN
68,A Nortje,6,6,22.2,0,217,9,3/42,24.11,9.71,14.8,0,0,NaN,NaN
70,M Ashwin,8,8,29.0,0,228,9,2/14,25.33,7.86,19.3,0,0,NaN,NaN
72,SP Narine,14,14,56.0,0,312,9,2/21,34.66,5.57,37.3,0,0,NaN,NaN
74,PVD Chameera,12,12,44.0,0,384,9,2/17,42.66,8.72,29.3,0,0,NaN,NaN
76,Mohammed Siraj,15,15,51.0,0,514,9,2/30,57.11,10.07,34.0,0,0,NaN,NaN
78,MM Ali,10,10,23.5,0,158,8,3/13,19.75,6.62,17.8,0,0,NaN,NaN
80,HH Pandya,15,10,30.3,0,222,8,3/17,27.75,7.27,22.8,0,0,NaN,NaN
82,RP Meredith,8,8,28.0,0,236,8,2/24,29.50,8.42,21.0,0,0,NaN,NaN
84,KR Sen,7,7,25.1,0,237,8,4/20,29.62,9.41,18.8,1,0,NaN,NaN
86,Mustafizur Rahman,8,8,32.0,0,244,8,3/18,30.50,7.62,24.0,0,0,NaN,NaN
88,J Suchith,5,5,18.0,0,140,7,2/12,20.00,7.77,15.4,0,0,NaN,NaN
90,PJ Cummins,5,5,19.5,0,212,7,3/22,30.28,10.68,17.0,0,0,NaN,NaN
92,AS Joseph,9,9,30.0,0,264,7,2/34,37.71,8.80,25.7,0,0,NaN,NaN
94,M Jansen,8,8,32.0,0,274,7,3/25,39.14,8.56,27.4,0,0,NaN,NaN

In [32]:
bo=pd.DataFrame(c['Player'])

In [64]:
bowlers=pd.concat([bowl_stats,bowl_stats1],axis=1)

In [54]:
bowling_figure['ch']=bo.Player

In [59]:
bowl_stats=bowling_figure.reset_index()

In [62]:
bowl_stats1=bo.reset_index()

In [67]:
bowlers.columns

Index(['index', 'Player', 'Mat', 'Inns', 'Overs', 'Mdns', 'Runs', 'Wkts',
       'BBI', 'Ave', 'Econ', 'SR', '4', '5', 'Team', 'franchise', 'ch',
       'index', 'Player'],
      dtype='object')

In [70]:
bowl_stats=bowlers[[ 'Player', 'Mat', 'Inns', 'Overs', 'Mdns', 'Runs', 'Wkts',
       'BBI', 'Ave', 'Econ', 'SR', '4', '5']]

In [82]:
bowl_stats.columns

Index(['Player', 'Player', 'Mat', 'Inns', 'Overs', 'Mdns', 'Runs', 'Wkts',
       'BBI', 'Ave', 'Econ', 'SR', '4', '5'],
      dtype='object')

In [83]:
bowl_stats[['Player',  'Mat', 'Inns', 'Overs', 'Mdns', 'Runs', 'Wkts',
       'BBI', 'Ave', 'Econ', 'SR', '4', '5']]

,Player,Player,Mat,Inns,Overs,Mdns,Runs,Wkts,BBI,Ave,Econ,SR,4,5
0,YS Chahal,(Rajasthan Royals),17,17,68.0,0,527,27,5/40,19.51,7.75,15.1,1,1
1,PWH de Silva,(Royal Challengers Bangalore),16,16,57.0,1,430,26,5/18,16.53,7.54,13.1,1,1
2,K Rabada,(Punjab Kings),13,13,48.0,0,406,23,4/33,17.65,8.45,12.5,2,0
3,Umran Malik,(Sunrisers Hyderabad),14,14,49.1,1,444,22,5/25,20.18,9.03,13.4,1,1
4,Kuldeep Yadav,(Delhi Capitals),14,14,49.4,0,419,21,4/14,19.95,8.43,14.1,2,0
5,JR Hazlewood,(Royal Challengers Bangalore),12,12,46.3,1,377,20,4/25,18.85,8.10,13.9,1,0
6,Mohammed Shami,(Gujarat Titans),16,16,61.0,0,488,20,3/25,24.40,8.00,18.3,0,0
7,HV Patel,(Royal Challengers Bangalore),15,15,53.3,2,410,19,4/34,21.57,7.66,16.8,1,0
8,Rashid Khan,(Gujarat Titans),16,16,63.5,0,421,19,4/24,22.15,6.59,20.1,1,0
9,M Prasidh Krishna,(Rajasthan Royals),17,17,66.3,3,551,19,3/22,29.00,8.28,21.0,0,0
10,T Natarajan,(Sunrisers Hyderabad),11,11,43.0,0,406,18,3/10,22.55,9.44,14.3,0,0
11,Avesh Khan,(Lucknow Super Giants),13,13,47.4,1,416,18,4/24,23.11,8.72,15.8,1,0
12,AD Russell,(Kolkata Knight Riders),14,13,28.1,0,278,17,4/5,16.35,9.86,9.9,1,0
13,DJ Bravo,(Chennai Super Kings),10,10,34.2,1,299,16,3/20,18.68,8.70,12.8,0,0
14,KK Ahmed,(Delhi Capitals),10,10,39.1,0,315,16,3/25,19.68,8.04,14.6,0,0
15,UT Yadav,(Kolkata Knight Riders),12,12,48.0,2,339,16,4/23,21.18,7.06,18.0,1,0
16,Mukesh Choudhary,(Chennai Super Kings),13,13,45.3,0,424,16,4/46,26.50,9.31,17.0,1,0
17,TA Boult,(Rajasthan Royals),16,16,62.0,3,492,16,2/18,30.75,7.93,23.2,0,0
18,JJ Bumrah,(Mumbai Indians),14,14,53.2,2,383,15,5/10,25.53,7.18,21.3,0,1
19,SN Thakur,(Delhi Capitals),14,14,48.2,1,473,15,4/36,31.53,9.78,19.3,1,0
20,Mohsin Khan,(Lucknow Super Giants),9,9,33.0,2,197,14,4/16,14.07,5.96,14.1,1,0
21,TG Southee,(Kolkata Knight Riders),9,9,35.0,0,275,14,3/20,19.64,7.85,15.0,0,0
22,RD Chahar,(Punjab Kings),13,13,46.4,1,360,14,3/25,25.71,7.71,20.0,0,0
23,JO Holder,(Lucknow Super Giants),12,12,41.3,0,391,14,3/31,27.92,9.42,17.7,0,0
24,DR Sams,(Mumbai Indians),11,11,42.0,0,370,13,4/30,28.46,8.80,19.3,1,0
25,Ravi Bishnoi,(Lucknow Super Giants),14,14,54.0,0,456,13,2/22,35.07,8.44,24.9,0,0
26,M Theekshana,(Chennai Super Kings),9,9,35.0,0,261,12,4/33,21.75,7.45,17.5,1,0
27,B Kumar,(Sunrisers Hyderabad),14,14,52.1,2,383,12,3/22,31.91,7.34,26.0,0,0
28,LH Ferguson,(Gujarat Titans),13,13,47.4,0,427,12,4/28,35.58,8.95,23.8,1,0
29,R Ashwin,(Rajasthan Royals),17,17,67.0,0,503,12,3/17,41.91,7.50,33.5,0,0
30,OC McCoy,(Rajasthan Royals),7,7,25.5,0,237,11,3/23,21.54,9.17,14.0,0,0
31,Yash Dayal,(Gujarat Titans),9,9,32.0,0,296,11,3/40,26.90,9.25,17.4,0,0
32,KH Pandya,(Lucknow Super Giants),14,12,38.0,1,265,10,3/19,26.50,6.97,22.8,0,0
33,Arshdeep Singh,(Punjab Kings),14,14,50.0,0,385,10,3/37,38.50,7.70,30.0,0,0
34,A Nortje,(Delhi Capitals),6,6,22.2,0,217,9,3/42,24.11,9.71,14.8,0,0
35,M Ashwin,(Mumbai Indians),8,8,29.0,0,228,9,2/14,25.33,7.86,19.3,0,0
36,SP Narine,(Kolkata Knight Riders),14,14,56.0,0,312,9,2/21,34.66,5.57,37.3,0,0
37,PVD Chameera,(Lucknow Super Giants),12,12,44.0,0,384,9,2/17,42.66,8.72,29.3,0,0
38,Mohammed Siraj,(Royal Challengers Bangalore),15,15,51.0,0,514,9,2/30,57.11,10.07,34.0,0,0
39,MM Ali,(Chennai Super Kings),10,10,23.5,0,158,8,3/13,19.75,6.62,17.8,0,0
40,HH Pandya,(Gujarat Titans),15,10,30.3,0,222,8,3/17,27.75,7.27,22.8,0,0
41,RP Meredith,(Mumbai Indians),8,8,28.0,0,236,8,2/24,29.50,8.42,21.0,0,0
42,KR Sen,(Rajasthan Royals),7,7,25.1,0,237,8,4/20,29.62,9.41,18.8,1,0
43,Mustafizur Rahman,(Delhi Capitals),8,8,32.0,0,244,8,3/18,30.50,7.62,24.0,0,0
44,J Suchith,(Sunrisers Hyderabad),5,5,18.0,0,140,7,2/12,20.00,7.77,15.4,0,0
45,PJ Cummins,(Kolkata Knight Riders),5,5,19.5,0,212,7,3/22,30.28,10.68,17.0,0,0
46,AS Joseph,(Gujarat Titans),9,9,30.0,0,264,7,2/34,37.71,8.80,25.7,0,0
47,M Jansen,(Sunrisers Hyderabad),8,8,32.0,0,274,7,3/25,39.14,8.56,27.4,0,0

In [116]:
bowl_stats.to_csv(r'C:\Data\bowler_stats.csv')

In [89]:
bf=pd.read_html("https://stats.espncricinfo.com/ci/engine/records/batting/most_runs_career.html?id=14452;type=tournament")

In [92]:
bat=bf[0]
bat

,Player,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,JC Buttler,17,17,2,863,116,57.53,579,149.05,4,4,0,83,45
1,(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals)
2,KL Rahul,15,15,3,616,103*,51.33,455,135.38,2,4,3,45,30
3,(Lucknow Super Giants),(Lucknow Super Giants),(Lucknow Super Giants),(Lucknow Super Giants),(Lucknow Super Giants),(Lucknow Super Giants),(Lucknow Super Giants),(Lucknow Super Giants),(Lucknow Super Giants),(Lucknow Super Giants),(Lucknow Super Giants),(Lucknow Super Giants),(Lucknow Super Giants),(Lucknow Super Giants)
4,Q de Kock,15,15,1,508,140*,36.28,341,148.97,1,3,0,47,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings)
96,MA Agarwal,13,12,0,196,52,16.33,160,122.50,0,1,1,23,6
97,(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings),(Punjab Kings)
98,R Ashwin,17,12,5,191,50,27.28,135,141.48,0,1,0,14,9
99,(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals),(Rajasthan Royals)

In [97]:
bat1=bat[0:100:2]
bat2=bat[1:100:2]

In [100]:
team=pd.DataFrame(bat2['Mat'])

In [103]:
franchise=team.reset_index()

In [105]:
main=bat1.reset_index()

In [106]:
main

,index,Player,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,0,JC Buttler,17,17,2,863,116,57.53,579,149.05,4,4,0,83,45
1,2,KL Rahul,15,15,3,616,103*,51.33,455,135.38,2,4,3,45,30
2,4,Q de Kock,15,15,1,508,140*,36.28,341,148.97,1,3,0,47,23
3,6,HH Pandya,15,15,4,487,87*,44.27,371,131.26,0,4,0,49,12
4,8,Shubman Gill,16,16,2,483,96,34.50,365,132.32,0,4,2,51,11
5,10,DA Miller,16,16,9,481,94*,68.71,337,142.72,0,2,0,32,23
6,12,F du Plessis,16,16,1,468,96,31.20,367,127.52,0,3,2,49,13
7,14,S Dhawan,14,14,2,460,88*,38.33,375,122.66,0,3,0,47,12
8,16,SV Samson,17,17,1,458,55,28.62,312,146.79,0,2,0,43,26
9,18,DJ Hooda,15,14,0,451,59,32.21,330,136.66,0,4,0,36,18
10,20,LS Livingstone,14,14,2,437,70,36.41,240,182.08,0,4,0,29,34
11,22,DA Warner,12,12,3,432,92*,48.00,287,150.52,0,5,1,52,15
12,24,Abhishek Sharma,14,14,0,426,75,30.42,320,133.12,0,2,1,47,13
13,26,Ishan Kishan,14,14,1,418,81*,32.15,348,120.11,0,3,1,45,11
14,28,RA Tripathi,14,14,3,413,76,37.54,261,158.23,0,3,2,40,20
15,30,SS Iyer,14,14,1,401,85,30.84,298,134.56,0,3,0,41,11
16,32,NT Tilak Varma,14,14,3,397,61,36.09,303,131.02,0,2,1,29,16
17,34,AK Markram,14,12,4,381,68*,47.62,274,139.05,0,3,0,25,19
18,36,D Padikkal,17,17,0,376,54,22.11,306,122.87,0,1,1,40,14
19,38,RD Gaikwad,14,14,0,368,99,26.28,291,126.46,0,3,2,33,14
20,40,N Rana,14,14,1,361,57,27.76,251,143.82,0,2,1,29,22
21,42,V Kohli,16,16,1,341,73,22.73,294,115.98,0,2,3,32,8
22,44,RR Pant,14,13,2,340,44,30.90,224,151.78,0,0,0,35,16
23,46,AD Russell,14,12,3,335,70*,37.22,192,174.47,0,1,2,18,32
24,48,RM Patidar,8,7,1,333,112*,55.50,218,152.75,1,2,0,27,18
25,50,KD Karthik,16,16,10,330,66*,55.00,180,183.33,0,1,1,27,22
26,52,WP Saha,11,11,1,317,68,31.70,259,122.39,0,3,1,40,7
27,54,SO Hetmyer,15,15,8,314,59*,44.85,204,153.92,0,1,0,21,21
28,56,N Pooran,14,13,5,306,64*,38.25,212,144.33,0,2,1,16,21
29,58,SA Yadav,8,8,1,303,68*,43.28,208,145.67,0,3,0,23,16
30,60,GJ Maxwell,13,13,2,301,55,27.36,178,169.10,0,1,1,31,15
31,62,S Dube,11,11,1,289,95*,28.90,185,156.21,0,2,1,22,16
32,64,PP Shaw,10,10,0,283,61,28.30,185,152.97,0,2,1,37,10
33,66,AT Rayudu,13,11,0,274,78,24.90,224,122.32,0,1,0,25,15
34,68,RG Sharma,14,14,0,268,48,19.14,223,120.17,0,0,1,28,13
35,70,YBK Jaiswal,10,10,0,258,68,25.80,194,132.98,0,2,0,28,10
36,72,JM Bairstow,11,11,0,253,66,23.00,175,144.57,0,2,0,34,9
37,74,DP Conway,7,7,1,252,87,42.00,173,145.66,0,3,1,22,12
38,76,MR Marsh,8,8,0,251,89,31.37,189,132.80,0,2,1,19,14
39,78,R Powell,14,12,2,250,67*,25.00,167,149.70,0,1,2,10,22
40,80,MM Ali,10,10,0,244,93,24.40,177,137.85,0,1,2,24,11
41,82,JM Sharma,12,10,2,234,44,29.25,143,163.63,0,0,0,22,12
42,84,MS Dhoni,14,13,6,232,50*,33.14,188,123.40,0,1,0,21,10
43,86,RV Uthappa,12,11,0,230,88,20.90,171,134.50,0,2,1,19,14
44,88,Shahbaz Ahmed,16,11,3,219,45,27.37,181,120.99,0,0,0,14,9
45,90,R Tewatia,16,12,5,217,43*,31.00,147,147.61,0,0,0,22,9
46,92,KS Williamson,13,13,2,216,57,19.63,231,93.50,0,1,1,16,8
47,94,PBB Rajapaksa,9,9,0,206,43,22.88,129,159.68,0,0,0,16,13
48,96,MA Agarwal,13,12,0,196,52,16.33,160,122.50,0,1,1,23,6
49,98,R Ashwin,17,12,5,191,50,27.28,135,141.48,0,1,0,14,9

In [107]:
batters=pd.concat([main,franchise],axis=1)

In [110]:
batters.columns

Index(['index', 'Player', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF', 'SR',
       '100', '50', '0', '4s', '6s', 'index', 'Mat'],
      dtype='object')

In [112]:
batsman=batters[['index', 'Player', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF', 'SR',
       '100', '50', '0', '4s', '6s', 'index']]

In [115]:
batsman.to_csv(r'C:\Data\batsman_stats.csv')

In [114]:
batsman

,index,index,Player,Mat,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,index,index
0,0,1,JC Buttler,17,(Rajasthan Royals),17,2,863,116,57.53,579,149.05,4,4,0,83,45,0,1
1,2,3,KL Rahul,15,(Lucknow Super Giants),15,3,616,103*,51.33,455,135.38,2,4,3,45,30,2,3
2,4,5,Q de Kock,15,(Lucknow Super Giants),15,1,508,140*,36.28,341,148.97,1,3,0,47,23,4,5
3,6,7,HH Pandya,15,(Gujarat Titans),15,4,487,87*,44.27,371,131.26,0,4,0,49,12,6,7
4,8,9,Shubman Gill,16,(Gujarat Titans),16,2,483,96,34.50,365,132.32,0,4,2,51,11,8,9
5,10,11,DA Miller,16,(Gujarat Titans),16,9,481,94*,68.71,337,142.72,0,2,0,32,23,10,11
6,12,13,F du Plessis,16,(Royal Challengers Bangalore),16,1,468,96,31.20,367,127.52,0,3,2,49,13,12,13
7,14,15,S Dhawan,14,(Punjab Kings),14,2,460,88*,38.33,375,122.66,0,3,0,47,12,14,15
8,16,17,SV Samson,17,(Rajasthan Royals),17,1,458,55,28.62,312,146.79,0,2,0,43,26,16,17
9,18,19,DJ Hooda,15,(Lucknow Super Giants),14,0,451,59,32.21,330,136.66,0,4,0,36,18,18,19
10,20,21,LS Livingstone,14,(Punjab Kings),14,2,437,70,36.41,240,182.08,0,4,0,29,34,20,21
11,22,23,DA Warner,12,(Delhi Capitals),12,3,432,92*,48.00,287,150.52,0,5,1,52,15,22,23
12,24,25,Abhishek Sharma,14,(Sunrisers Hyderabad),14,0,426,75,30.42,320,133.12,0,2,1,47,13,24,25
13,26,27,Ishan Kishan,14,(Mumbai Indians),14,1,418,81*,32.15,348,120.11,0,3,1,45,11,26,27
14,28,29,RA Tripathi,14,(Sunrisers Hyderabad),14,3,413,76,37.54,261,158.23,0,3,2,40,20,28,29
15,30,31,SS Iyer,14,(Kolkata Knight Riders),14,1,401,85,30.84,298,134.56,0,3,0,41,11,30,31
16,32,33,NT Tilak Varma,14,(Mumbai Indians),14,3,397,61,36.09,303,131.02,0,2,1,29,16,32,33
17,34,35,AK Markram,14,(Sunrisers Hyderabad),12,4,381,68*,47.62,274,139.05,0,3,0,25,19,34,35
18,36,37,D Padikkal,17,(Rajasthan Royals),17,0,376,54,22.11,306,122.87,0,1,1,40,14,36,37
19,38,39,RD Gaikwad,14,(Chennai Super Kings),14,0,368,99,26.28,291,126.46,0,3,2,33,14,38,39
20,40,41,N Rana,14,(Kolkata Knight Riders),14,1,361,57,27.76,251,143.82,0,2,1,29,22,40,41
21,42,43,V Kohli,16,(Royal Challengers Bangalore),16,1,341,73,22.73,294,115.98,0,2,3,32,8,42,43
22,44,45,RR Pant,14,(Delhi Capitals),13,2,340,44,30.90,224,151.78,0,0,0,35,16,44,45
23,46,47,AD Russell,14,(Kolkata Knight Riders),12,3,335,70*,37.22,192,174.47,0,1,2,18,32,46,47
24,48,49,RM Patidar,8,(Royal Challengers Bangalore),7,1,333,112*,55.50,218,152.75,1,2,0,27,18,48,49
25,50,51,KD Karthik,16,(Royal Challengers Bangalore),16,10,330,66*,55.00,180,183.33,0,1,1,27,22,50,51
26,52,53,WP Saha,11,(Gujarat Titans),11,1,317,68,31.70,259,122.39,0,3,1,40,7,52,53
27,54,55,SO Hetmyer,15,(Rajasthan Royals),15,8,314,59*,44.85,204,153.92,0,1,0,21,21,54,55
28,56,57,N Pooran,14,(Sunrisers Hyderabad),13,5,306,64*,38.25,212,144.33,0,2,1,16,21,56,57
29,58,59,SA Yadav,8,(Mumbai Indians),8,1,303,68*,43.28,208,145.67,0,3,0,23,16,58,59
30,60,61,GJ Maxwell,13,(Royal Challengers Bangalore),13,2,301,55,27.36,178,169.10,0,1,1,31,15,60,61
31,62,63,S Dube,11,(Chennai Super Kings),11,1,289,95*,28.90,185,156.21,0,2,1,22,16,62,63
32,64,65,PP Shaw,10,(Delhi Capitals),10,0,283,61,28.30,185,152.97,0,2,1,37,10,64,65
33,66,67,AT Rayudu,13,(Chennai Super Kings),11,0,274,78,24.90,224,122.32,0,1,0,25,15,66,67
34,68,69,RG Sharma,14,(Mumbai Indians),14,0,268,48,19.14,223,120.17,0,0,1,28,13,68,69
35,70,71,YBK Jaiswal,10,(Rajasthan Royals),10,0,258,68,25.80,194,132.98,0,2,0,28,10,70,71
36,72,73,JM Bairstow,11,(Punjab Kings),11,0,253,66,23.00,175,144.57,0,2,0,34,9,72,73
37,74,75,DP Conway,7,(Chennai Super Kings),7,1,252,87,42.00,173,145.66,0,3,1,22,12,74,75
38,76,77,MR Marsh,8,(Delhi Capitals),8,0,251,89,31.37,189,132.80,0,2,1,19,14,76,77
39,78,79,R Powell,14,(Delhi Capitals),12,2,250,67*,25.00,167,149.70,0,1,2,10,22,78,79
40,80,81,MM Ali,10,(Chennai Super Kings),10,0,244,93,24.40,177,137.85,0,1,2,24,11,80,81
41,82,83,JM Sharma,12,(Punjab Kings),10,2,234,44,29.25,143,163.63,0,0,0,22,12,82,83
42,84,85,MS Dhoni,14,(Chennai Super Kings),13,6,232,50*,33.14,188,123.40,0,1,0,21,10,84,85
43,86,87,RV Uthappa,12,(Chennai Super Kings),11,0,230,88,20.90,171,134.50,0,2,1,19,14,86,87
44,88,89,Shahbaz Ahmed,16,(Royal Challengers Bangalore),11,3,219,45,27.37,181,120.99,0,0,0,14,9,88,89
45,90,91,R Tewatia,16,(Gujarat Titans),12,5,217,43*,31.00,147,147.61,0,0,0,22,9,90,91
46,92,93,KS Williamson,13,(Sunrisers Hyderabad),13,2,216,57,19.63,231,93.50,0,1,1,16,8,92,93
47,94,95,PBB Rajapaksa,9,(Punjab Kings),9,0,206,43,22.88,129,159.68,0,0,0,16,13,94,95
48,96,97,MA Agarwal,13,(Punjab Kings),12,0,196,52,16.33,160,122.50,0,1,1,23,6,96,97
49,98,99,R Ashwin,17,(Rajasthan Royals),12,5,191,50,27.28,135,141.48,0,1,0,14,9,98,99